repositories:
  - name: spark-operator
    url: https://kubeflow.github.io/spark-operator
  - name: minio
    url: https://charts.min.io/

releases:
  - name: spark-operator
    namespace: spark-operator
    chart: spark-operator/spark-operator
    # values:
  - name: minio
    namespace: minio
    chart: minio/minio
    values:
      - resources:
          requests:
            memory: 512Mi
        replicas: 1
        persistence:
          enabled: false
        mode: standalone
        rootUser: rootuser
        rootPassword: rootpass123
