apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: distributed-data
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: spark:3.5.5
  mainClass: FirstApp
  mainApplicationFile: http://minio.minio.svc.cluster.local:9000/data/distributed_data.jar
  driver:
    cores: 1
    memory: 512m
    labels:
      version: 3.5.5
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: 512m
    labels:
      version: 3.5.5
